version: '3'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "/wait && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgis

    environment:
      WAIT_HOSTS: postgis:5432

  postgis:
    image: kartoza/postgis:12.1 #postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD