version: '3'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "/wait && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgis
      - mongodb
    environment:
      WAIT_HOSTS: postgis:5432, mongodb:27017

  postgis:
    image: kartoza/postgis:12.1 #postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    logging:  
      driver: none
       
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    logging:  
      driver: none 


