version: '3'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - db
  db:
    image: postgres #kartoza/postgis:12.1
    environment: 
      - POSTGRES_PASSWORD=test