# Generated by Django 3.1.6 on 2021-02-02 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210201_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 13, 47, 52, 636341, tzinfo=utc)),
        ),
    ]
