# Generated by Django 3.1.6 on 2021-02-03 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210202_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='slug',
            field=models.SlugField(blank=True, max_length=95, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 8, 38, 59, 93569, tzinfo=utc)),
        ),
    ]
